[2021-03-31 03:00:25,018] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ingestion-pipeline.IngestingData 2021-03-31T00:00:00+00:00 [queued]>
[2021-03-31 03:00:25,032] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ingestion-pipeline.IngestingData 2021-03-31T00:00:00+00:00 [queued]>
[2021-03-31 03:00:25,032] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-31 03:00:25,032] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-31 03:00:25,032] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-31 03:00:25,046] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): IngestingData> on 2021-03-31T00:00:00+00:00
[2021-03-31 03:00:25,050] {standard_task_runner.py:52} INFO - Started process 15866 to run task
[2021-03-31 03:00:25,056] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ingestion-pipeline', 'IngestingData', '2021-03-31T00:00:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ingestion.py', '--cfg-path', '/tmp/tmp47io93m6', '--error-file', '/tmp/tmp7ee4bta4']
[2021-03-31 03:00:25,056] {standard_task_runner.py:77} INFO - Job 9: Subtask IngestingData
[2021-03-31 03:00:25,091] {logging_mixin.py:104} INFO - Running <TaskInstance: ingestion-pipeline.IngestingData 2021-03-31T00:00:00+00:00 [running]> on host prathamesh-VirtualBox
[2021-03-31 03:00:25,122] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ingestion-pipeline
AIRFLOW_CTX_TASK_ID=IngestingData
AIRFLOW_CTX_EXECUTION_DATE=2021-03-31T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-31T00:00:00+00:00
[2021-03-31 03:00:25,122] {python.py:118} INFO - Done. Returned value was: None
[2021-03-31 03:00:25,125] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=ingestion-pipeline, task_id=IngestingData, execution_date=20210331T000000, start_date=20210331T070025, end_date=20210331T070025
[2021-03-31 03:00:25,143] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-31 03:00:25,179] {local_task_job.py:146} INFO - Task exited with return code 0
